### ISSUE TITLE
[BUG] Null error on profiles

### ISSUE THREAD

**Issue by Bluscream** [TheHCJ/Quacker#8] opened 2024-03-28 02:47 UTC
**Describe the bug**
Profiles not worky

**To Reproduce**
1. Click any profile

**Expected behavior**
a wild profile appears

**Screenshots**
![Screenshot_2024-03-28_03-44-54.png](https://github.com/TheHCJ/Quacker/assets/3318223/981c98f8-95b8-4b5b-8ba5-40f3901e0258)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] lenovo tablet
 - OS: [e.g. iOS8.1] android 14
 - Browser [e.g. stock browser, safari] none
 - Version [e.g. 22] 14

**Additional context**

**Comment by TheHCJ** [comment] 2024-03-28 07:02
What profile is this happening on so I can reproduce this error

**Comment by Bluscream** [comment] 2024-03-28 07:21
Any of my subscriptions; take @elonmusk for example

**Comment by TheHCJ** [comment] 2024-03-28 16:46
Ok, thanks I suspect it's due to an error in the  Regex filtering which I will remove in a future version for stability

**Comment by TheHCJ** [comment] 2024-03-28 19:39
Would you mind testing out the latest ci build and let me know if you still experience this error

**Comment by Bluscream** [comment] 2024-03-28 20:28
Same error with latest ci artifact

**Comment by TheHCJ** [comment] 2024-03-29 11:14
Have you tried deleting cookies and re-login on your account?

**Comment by Bluscream** [comment] 2024-03-29 16:30
When i try tog in i get a 2fa code email from X but no way to enter it in the aop

**Comment by TheHCJ** [comment] 2024-03-29 19:20
Currently login doesn't work with 2FA

**Comment by strongville** [comment] 2024-03-30 01:07
Can confirm this issue also happens on my 2FA-enabled account, maybe a PSA should be put on README to close this issue?

**Comment by Bluscream** [comment] 2024-03-30 01:49
> Can confirm this issue also happens on my 2FA-enabled account, maybe a PSA should be put on README to close this issue?

Better to put the info in the app right next to the login screen.
Also the same bug appears when not logged in at all.

**Comment by TheHCJ** [comment] 2024-04-07 09:12
> > Can confirm this issue also happens on my 2FA-enabled account, maybe a PSA should be put on README to close this issue?
> 
> Better to put the info in the app right next to the login screen. Also the same bug appears when not logged in at all.

I have added this into the latest ci build until I find a way to implement #9

**Comment by TheHCJ** [comment] 2024-04-07 15:24
I have added a notice under the `Accounts` category in [v3.3.0](https://github.com/TheHCJ/Quacker/releases/tag/v3.3.0)

**Closed** 2024-06-16 14:13 UTC
Labels: bug, wontfix
