### ISSUE TITLE
[BUG] Quote Tweets do not show in feed

### ISSUE THREAD

**Issue by ondern** [TheHCJ/Quacker#7] opened 2023-05-13 17:43 UTC
**Describe the bug**
Quoted tweets do not show in feeds.

**To Reproduce**
1. Go to customised group feed
2. See a quotation tweet
3. Quotation does not show but when clicked the tweet details, it can be displayed.

**Screenshots**
None

**Device** 
Device: Mi9T 
OS: Android 13 
Version: v0.2

**Does this happen on the latest [Fritter](https://github.com/jonjomckay/fritter/releases) release?**
Yes

**Comment by ondern** [comment] 2023-05-13 17:45
https://github.com/TheHCJ/Quacker/assets/109258788/79398684-a7bb-4458-8e33-3de3a9cb7302

**Comment by ondern** [comment] 2023-05-13 19:04
https://twitter.com/portovechiaaa/status/1657403104759775246

![Screenshot_20230513-220335_Quacker](https://github.com/TheHCJ/Quacker/assets/109258788/6a41c547-ba92-4989-a5eb-88a47fbf4b99)

**Comment by TheHCJ** [comment] 2023-05-13 19:57
> https://twitter.com/portovechiaaa/status/1657403104759775246
> 
> ![Screenshot_20230513-220335_Quacker](https://user-images.githubusercontent.com/109258788/238152508-6a41c547-ba92-4989-a5eb-88a47fbf4b99.png)

In future please create a new issue for other bugs, in this case I have created one at #8.

**Comment by TheHCJ** [comment] 2023-05-18 20:49
This bug should be fixed, check the ci builds

**Comment by AndiDink00x** [comment] 2023-05-24 15:05
I see that the issue is duplicated to https://github.com/TheHCJ/Quacker/issues/27

**Comment by TheHCJ** [comment] 2023-06-07 16:38
Having issues fixing this due to it being an issue with tweet searching. I will look into another solution

**Comment by j-fbriere** [comment] 2023-06-07 19:02
@TheHCJ Here is the fix for the quoted tweets in feeds.

[fix_7.patch](https://github.com/TheHCJ/Quacker/files/11681032/fix_7.patch)

**Closed** 2023-06-07 19:43 UTC
Labels: bug, feed

**Comment by ondern** [comment] 2023-06-07 20:29
@TheHCJ Could you please add a canary release daily frequently so beta users can test before stable release?

Thanks
Önder

**Comment by j-fbriere** [comment] 2023-06-07 20:41
You could install the last ci build's [apk file](https://github.com/TheHCJ/Quacker/suites/13446626392/artifacts/737372726).

**Comment by TheHCJ** [comment] 2023-06-07 20:43
I'll look into it for 3.0.0
