### ISSUE TITLE
[BUG] Quoted content and links are not visible.

### ISSUE THREAD

**Issue by rsssxd** [TheHCJ/Quacker#27] opened 2023-05-19 07:07 UTC
Quoted Tweet posts are not displayed correctly in the stream.
![Screenshot_20230519-095624_Quacker_1](https://github.com/TheHCJ/Quacker/assets/60405617/907b341a-4bf5-4acb-aa01-c682ee2c7461)
![Screenshot_20230519-095628_Quacker](https://github.com/TheHCJ/Quacker/assets/60405617/ef69d2df-1b66-42f8-87c8-c36e4de44cc3)

If the tweet is fully opened, the quoted tweet appears.

The other problem is that tweets with links appear incomplete. Please open this link on Quacker.
https://nitter.net/yenisafak/status/1659450030489567238
![Screenshot_20230519-100209_Quacker](https://github.com/TheHCJ/Quacker/assets/60405617/428367e1-0083-4a39-84ce-c7865d87e408)
![Screenshot_20230519-100226_Mulch](https://github.com/TheHCJ/Quacker/assets/60405617/31fadca1-bb90-485d-ba17-1999f53cbcff)

**Comment by TheHCJ** [comment] 2023-05-19 16:53
Duplicate of #7, and already solved for next release

**Comment by rsssxd** [comment] 2023-05-19 17:26
I checked the latest CI build. The error persists.

**Comment by rsssxd** [comment] 2023-05-19 20:40
@TheHCJ Two bugs persist in the latest versions. Please reopen the bug.

**Comment by j-fbriere** [comment] 2023-05-24 06:42
@TheHCJ This is to fix the bug of invisible quoted content in tweet feed and also in tweet detail.

[fix_27.patch](https://github.com/TheHCJ/Quacker/files/11551261/fix_27.patch)

**Comment by TheHCJ** [comment] 2023-05-24 06:54
Thanks for the patch, I will merge this once I have time to

**Closed** 2023-05-24 18:06 UTC
Labels: bug

**Comment by j-fbriere** [comment] 2023-05-24 20:34
@rsssxd Please give a precise example of the problem you are experiencing.
Eg. An url of a tweet, what it looks like in the browser or with nitter, and what it looks like in Quacker.

**Comment by rsssxd** [comment] 2023-05-24 20:37
@j-fbriere 

There are two images I posted at the top. Quote Tweet posts are visible if the Tweet is opened in a new tab.

**Comment by j-fbriere** [comment] 2023-05-24 20:39
@rsssxd There is no url in your first example at the top. Really hard for me to try to reproduce.

**Comment by rsssxd** [comment] 2023-05-24 20:40
@j-fbriere  https://twitter.com/malikejder47/status/1661468377863409666

**Comment by j-fbriere** [comment] 2023-05-24 20:45
@rsssxd I see no difference between twitter, nitter and Quacker (latest ci build) with the URL toy just provided.

**Comment by rsssxd** [comment] 2023-05-24 20:47
@j-fbriere 

https://github.com/TheHCJ/Quacker/assets/60405617/c520c348-7149-4d25-a8d3-639483fa6cac
